### PR TITLE
SLIDESDOC-318: Updated "Chart Workbook" in J, C, P

### PR DESCRIPTION
**Pull request by EmSeriki**
@nikolaysaulyak @stasmiroshnichenko @petrtetenko 

Please, search for "xxx" and add the relevant code snippets and then delete "xxx".

### CODE REVIEW

**Review by stasmiroshnichenko — APPROVED** [review]

**Comment by vlukyanets** [comment]
@nikolaysaulyak

**Review by nikolaysaulyak — APPROVED** [review]

**Review by petrtetenko — CHANGES_REQUESTED** [review]
@yury-knml @EmSeriki 

Please, pay attention, that the C# code snippet "Specify Data Source Type" contains of the following code:

```
IChartDataPoint point = series[0].DataPoints.GetOrCreateDataPointByIdx(2);
point = series[0].DataPoints.GetOrCreateDataPointByIdx(4);
```

The second line doesn't make sense (well, or the first one)

**Review by yury-knml — APPROVED** [review]

**Review by petrtetenko — APPROVED** [review]

**Comment by EmSeriki** [comment]
@nikolaysaulyak You may want to review the C++ snippets after recent changes.

**Comment by EmSeriki** [comment]
@stasmiroshnichenko You may want to review the Python snippets (see recent changes in .NET).

 @nikolaysaulyak You may want to review the C++ snippets (see recent changes in .NET).

**Review by stasmiroshnichenko — APPROVED** [review]

**Review by nikolaysaulyak — APPROVED** [review]

**Comment by valentynlukianets-aspose** [comment]
@nikolaysaulyak Updated

**Review by valentynlukianets-aspose — APPROVED** [review]

**Review by stasmiroshnichenko — APPROVED** [review]

**Pull request merged**
