### PR TITLE
SLIDESDOC-334: Print Presentation in J, C, P

### PR DESCRIPTION
**Pull request by EmSeriki**
@petrtetenko @nikolaysaulyak 

Please, search for "xxx" and add the relevant code snippets and then delete "xxx". You may also want to provide more info on classes and methods used for for printing operations in Java and C++.

### CODE REVIEW

**Review by petrtetenko — APPROVED** [review]
@EmSeriki 

We can't add this article to Aspose.Slides for Java, because printing is not available (SLIDESJAVA-34379).

**Comment by EmSeriki** [comment]
> @EmSeriki
> 
> We can't add this article to Aspose.Slides for Java, because printing is not available (SLIDESJAVA-34379).

Alright, thanks for the info.

**Comment by valentynlukianets-aspose** [comment]
@nikolaysaulyak

**Comment by nikolaysaulyak** [comment]
> > @EmSeriki
> > We can't add this article to Aspose.Slides for Java, because printing is not available (SLIDESJAVA-34379).
> 
> Alright, thanks for the info.
> 
> @nikolaysaulyak is printing also unavailable in Aspose.Slides for C++?

@EmSeriki

Printing is not supported in Aspose.Slides for С++ (SLIDESCPP-1791).

**Review by nikolaysaulyak — APPROVED** [review]

**Review by stasmiroshnichenko — APPROVED** [review]

**Pull request merged**
