### PR TITLE
Fixed Broken Links

### PR DESCRIPTION
**Pull request by aliahmedaspose**

### CODE REVIEW

**Comment by EmSeriki** [comment]
@aliahmedaspose Hi. Thanks. 

Is there a reason you replaced https web links with folder links? Do we have a policy for links?

**Comment by muhammad-ijaz** [comment]
> @aliahmedaspose Hi. Thanks.
> 
> Is there a reason you replaced https web links with folder links? Do we have a policy for links?

@EmSeriki 
Can you please further elaborate your question with an example (what types of links you are calling folder links)?

As far as the changes are concerned, these are all about broken and obsolete/redirected links. As per my initial review, @aliahmedaspose did not fix internal links correctly e.g. "/slides/java/features-overview" was incorrect link because Hugo adds / at the end of each link and if it is not added, we will need a 301 redirect to "/slides/java/features-overview/". To resolve this issue, we need to add a / at the end of every internal link, so the correct fixed link was "/slides/java/features-overview" but @aliahmedaspose has added it as "https://docs.aspose.com/slides/java/features-overview/" which is wrong. He is working on fixing this issue and it will be fixed soon. 

Please share if you were talking about a different issue?

**Comment by EmSeriki** [comment]
> > @aliahmedaspose Hi. Thanks.
> > Is there a reason you replaced https web links with folder links? Do we have a policy for links?
> 
> @EmSeriki
> Can you please further elaborate your question with an example (what types of links you are calling folder links)?
> 
> As far as the changes are concerned, these are all about broken and obsolete/redirected links. As per my initial review, @aliahmedaspose did not fix internal links correctly e.g. "/slides/java/features-overview" was incorrect link because Hugo adds / at the end of each link and if it is not added, we will need a 301 redirect to "/slides/java/features-overview/". To resolve this issue, we need to add a / at the end of every internal link, so the correct fixed link was "/slides/java/features-overview/" but @aliahmedaspose has added it as "https://docs.aspose.com/slides/java/features-overview/" which is wrong. He is working on fixing this issue and it will be fixed soon.
> 
> Please share if you were talking about a different issue?

Thanks again for the explanation. Oh, I was actually about a slightly different issue:

I wanted to know if we now have a policy to replace all https web links (https://docs.aspose.com/slides/java/features-overview/)  with folder links (/slides/java/features-overview/).

**Comment by muhammad-ijaz** [comment]
@EmSeriki 

Yes, you are right. We should use folder links for all internal links because https://docs.aspose.com is added automatically by Hugo at the start of the link, so we should start the internal docs links from /slides/ or any other product name in case of other products.

**Review by muhammad-ijaz — APPROVED** [review]

**Pull request merged**
